export default [
  {
    path: '/grid',
    component: 'src/containers/Grid',
    name: 'Grid',
    category: 'layout',
  },
  {
    path: '/containers',
    component: 'src/containers/Containers',
    name: 'Containers',
    category: 'layout',
  },
  {
    path: '/sections',
    component: 'src/containers/Sections',
    name: 'Sections',
    category: 'layout',
  },
  {
    path: '/colors',
    component: 'src/containers/Colors',
    name: 'Colors',
    category: 'base',
  },
  {
    path: '/typography',
    component: 'src/containers/Typography',
    name: 'Typography',
    category: 'base',
  },
  {
    path: '/buttons',
    component: 'src/containers/Buttons',
    name: 'Buttons',
    category: 'base',
  },
  {
    path: '/forms',
    component: 'src/containers/Forms',
    name: 'Forms',
    category: 'base',
  },
  {
    path: '/tables',
    component: 'src/containers/Tables',
    name: 'Tables',
    category: 'base',
  },
  {
    path: '/cards',
    component: 'src/containers/Cards',
    name: 'Cards',
    category: 'components',
  },
  {
    path: '/carousels',
    component: 'src/containers/Carousels',
    name: 'Carousels',
    category: 'components',
  },
  {
    path: '/dropdowns',
    component: 'src/containers/Dropdowns',
    name: 'Dropdowns',
    category: 'components',
  },
  {
    path: '/modals',
    component: 'src/containers/Modals',
    name: 'Modals',
    category: 'components',
  },
  {
    path: '/notices',
    component: 'src/containers/Notices',
    name: 'Notices',
    category: 'components',
  },
  {
    path: '/pagination',
    component: 'src/containers/Pagination',
    name: 'Pagination',
    category: 'components',
  },
  {
    path: '/toggles',
    component: 'src/containers/Toggles',
    name: 'Toggles',
    category: 'components',
  },
  {
    path: '/tooltips',
    component: 'src/containers/Tooltips',
    name: 'Tooltips',
    category: 'components',
  },
  {
    path: '/utilities',
    component: 'src/containers/Utilities',
    name: 'Utilities',
    category: 'other',
  },
];
