[build]
  publish = "build/"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run stage"

[context.branch-deploy]
  command = "npm run stage"

[redirects]
  from = "/*"
  to = "/"
  status = 301
